### ISSUE TITLE
Feature request: Remove edges

### ISSUE THREAD

**Issue by jsphstls** [cytoscape/cytoscape.js-edgehandles#146]
This extension is super interesting and the demo works very well.

In the demo, an unlimited number of connections can be made, thought there is no way to remove them. When mousing over a node the edge handle appears. When hovering over an edge a remove option could appear.

Removing edges could be a different extension altogether, or maybe there is a solution that already pairs well with this one?

**Comment by jsphstls** [comment]
Perhaps a better way to approach this is to allow edges to be retargeted, so the heads can be grabbed and moved to other nodes. If the head is not given a new target, the edge disappears the same way that it does when dragging new edges.

**Comment by dwagin** [comment]
Maybe this will help you:
[Cytoscape.js control module](https://gitlab.com/max.kutkov/cytoscape.js-controls)

**Comment by maxkfranz** [comment]
I think that the extension should be simplified in a future version, removing the handle node completely.  If you want to draw a handle, you could use an extension like cytoscape-popper to show any kind of handle you want.  The use of the handle node is kind of hacky.

In the same vein of this simplification, your proposed feature could just be API that restarts the gesture for an existing edge.  You can then initiate the restart of an edge with any kind of UI you want -- a button, a popper, or simply an event like tapdragging on an edge.  So a couple of functions like `restartTarget(edge)` and restartSource(edge)` would suffice.

If you're interested in making those functions, @jsphstls, I could try to prioritise the simplifications I mentioned so that we could make a release that would fit well with your feature.

**Comment by jsphstls** [comment]
Tap-drag on the edge makes sense, no need for a handle if the entire edge can be selected. I have not implemented this extension yet but after that I can try out new functions.

**Comment by maxkfranz** [comment]
Yes, that’s the simplest case.  However, that case has the assumption that you always want to amend the same side — target or source — of an edge.

In any case, the addition of simple `restartSource()` and `restartTarget()` functions to this extension would probably suffice for your use case.  That would be easier than creating an entirely new extension, and the restart functions would be a good fit with the existing functions in this extension.  If you only need `restartTarget()`, that would probably only require minor changes to the existing `start()` function.  Just a thought
