### ISSUE TITLE
Multiple edges from one node in Cytoscape

### ISSUE THREAD

**Issue by BBarBiel** [cytoscape/cytoscape.js-edgehandles#172]
Hi everyone,
I have a question regarding Cytoscape_v3.9.1. I made a network by entering Entrez IDs into the STRING protein query, however I need to add a node that interacts with all of the nodes of this network which could not be found by STRING app. Is it possible to do this in Cytoscape or do I have to input a file of some kind to do that? At first I wanted to merge this string network and a network containing the interaction between this node in particular and the other nodes, but I always get an error: Index 0 out of bounds for length 0 and I have no idea what this means. When I tried to look at the advanced options of merge there was a matching attribute written in read that said Change me! when I hovered my mouse over it, I have no idea how to fix this either.
It would be very much appreciated if anyone could help me.

**Comment by AlexanderPico** [comment]
Hi @BBarBiel. Merging STRING networks with non-STRING network will be tricky because STRING has a bunch of custom named columns (so "name" from STRING and "name" from another source will not match).  But, you have a few options:

1. merge two STRING networks. If you can get the other network from STRING?
2. right-click on STRING network and `Add > Node`. You can literally add nodes and edges by clicking on the screen.
3. get _really_ familiar with the Merge app, starting with [the manual ](https://manual.cytoscape.org/en/stable/Merge.html)and then trying a bunch of simpler cases until you attain advanced skills with this complex tool. 

As a final note: This is the Issue tracker for cytoscape.js, which is completely different from Cytoscape :)  This issue will be closed (due to irrelevance), but feel free to follow up and ask more questions about Cytoscape [at BioStars](https://www.biostars.org/t/cytoscape/) (and tag with `cytoscape`).
