### ISSUE TITLE
Nodes Not Grabbable After Edgehandle

### ISSUE THREAD

**Issue by karchjd** [cytoscape/cytoscape.js-edgehandles#183]
This is probably my mistake but maybe it is a bug?

https://stackoverflow.com/questions/76514570/cytoscape-js-problems-with-autoungrabify-or-autolock

**Comment by karchjd** [comment]
Either way, I would be very thankful for some help, if you have some time to spare.

**Comment by maxkfranz** [comment]
Possibly:  You have a listener on all edges, and you likely have presumed that the edges you are handling are all newly, user-created edges.  That might not be true in all cases, e.g. preview elements.  In any case, it’s best to be explicit about the sort of elements you are handling and it’s best to use the events of this extension when you really mean things like ‘an event for an edge drawn by a user is added using this extension’.  There are classes and events that help you with this sort of thing, documented in the readme.

Definitely:  Use the [Chrome debugger](https://developer.chrome.com/docs/devtools/) and step through your code.  Whatever your issue is will then become obvious.  If you notice a bug in the extension, please post it here.

**Comment by jondavis847** [comment]
I'm having the same issue. After connecting any nodes with edge-handles in 4.0.1, I can no longer grab any nodes. I even added the following code to my ehcomplete event to try to force all eles back to grabbable, but log still shows all nodes are not grabbable, even after specifically grabifying them.

```javascript 
cy.nodes().forEach(function (ele) {
            ele.grabify();
            console.log(ele.grabbable());
        }) // all nodes are false
```

**Comment by maxkfranz** [comment]
Is this reproducible in the demo in the readme?

If not, let's post a reproducible jsbin. You can fork this one to put one together quickly:  http://jsbin.com/fiqugiq

**Comment by jondavis847** [comment]
I was able reproduce here. I use left shift document events to enable and disable draw mode. Confirmed that using buttons for draw mode did not cause the issue.

https://jsfiddle.net/1Lv72pho/1/

**Comment by maxkfranz** [comment]
I couldn’t reproduce it on my iPad pro using the physical keyboard and trackpad in Safari.  That should have the same keyboard and mouse events as a Macbook.

Would you upload a video with the exact steps you took in the demo to reproduce the issue?

I can drag nodes around just fine after drawing an edge.
