### ISSUE TITLE
Option to specify multiple handlePosition(s)

### ISSUE THREAD

**Issue by Brendan92** [cytoscape/cytoscape.js-edgehandles#60]
Is there a way to specify multiple positions for the handle as per node? For example if the node has css class 'x' the handlePosition: 'left middle | right middle', and if the node has css class 'y' the handlePosition: 'top middle | top bottom'

Essentially I'm talking about two questions/suggestions:
1. Multiple handelPositions
2. Different positions for different css class nodes

Can this be done?

**Comment by maxkfranz** [comment]
There's already another extension that does that: https://github.com/frankiex/cytoscape.js-edge-editation

**Comment by emmasuzuki** [comment]
A different approach but I made a multiple handles solution using angles for cytoscape.js-edgehandles. 

Here is a diff: https://github.com/cytoscape/cytoscape.js-edgehandles/compare/master...emmasuzuki:master#diff-bf46f115a4de5512482237689d4a2c8a

I am happy to contribute to original if you like it. Also, I am open to any further modification. If original proposal `handlePosition: 'top middle | top bottom'` works better, I can modify my code.

**Comment by maxkfranz** [comment]
@emmasuzuki It would be great if you could put your changes into a PR!  It would make sense to support the existing options though, so maybe a `handlePosition` string could be converted into an internal angle?

**Comment by emmasuzuki** [comment]
@maxkfranz Right now, I do backward compatible by letting user pass either `handlePosition` OR `handlePositionAngles`. User still can keep using `handlePosition: 'middle top'`. If user pass `handlePositionAngles` but not `handlePosition`, then angles are used to put handles. 

Do you like to keep just `handleOption` param and parse string so that if it is number, consider as angle and if not try match against preserved keywords (top, middle, ...)? 

So for instance user can pass,
- `handlePosition: 'right middle,left middle'` 
- `handlePosition: '0,180'`                                
- `handlePosition: 'right middle,180'`

everything translates into 0,180 angles?

**Comment by maxkfranz** [comment]
@emmasuzuki That sounds like a good plan.  Thanks

**Comment by maxkfranz** [comment]
Create one instance per handle
