### ISSUE TITLE
"Always on" edgehandles?

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js-edgehandles#64]
Have this been considered and rejected or would pull requests be welcome? 

I'm thinking basically an option to not have this displayed on hover/mouseover, but rather all the time?

**Comment by maxkfranz** [comment]
Do you mean draw mode?

**Comment by buffpojken** [comment]
Yep, as in - always display the handle

**Comment by maxkfranz** [comment]
Draw mode is enabled like this `cy.edgehandles('drawon')` https://github.com/cytoscape/cytoscape.js-edgehandles#extension-functions

**Comment by buffpojken** [comment]
Hmm, is that really the same thing? I just did a quick test and while 'drawon' enables the functionality, no handles are drawn?

**Comment by maxkfranz** [comment]
Oh you mean draw handles on all elements at the same time?  That would add a lot of complexity to the project, because it would potentially have to be synched every frame.  With how it is now, most of the time no handle is drawn.  And a handle is drawn only if the node or viewport haven't altered where the handle would be drawn.

For the all nodes all the time usecase, it would be a lot simpler to never draw the builtin handle and use a background image for the handle on all the nodes.  That's something the extension can't really set though.  Whereas a dev can carefully set multiple background images per node in the stylesheet, the extension would have to override the images to set the handle image at that level.

**Comment by buffpojken** [comment]
Aha, makes sense! I'll investigate drawMode further - sounds like it would resolve the issue neatly!

On a second, somewhat unrelated, note - does `dev can carefully set multiple background images per node` actually mean that one can have multiple, concurrent background-images on a node? I was under the impression that that wasn't possible?

**Comment by maxkfranz** [comment]
Multiple background images is a feature in 3.1.  All the bg img properties can take on array values with each image having a particular index in each array.

**Comment by buffpojken** [comment]
Epic, I had no idea! Thanks! 

I'll close this since drawMode + multiple backgrounds solve this in a neater way.
