### ISSUE TITLE
Add changelog.md file

### ISSUE THREAD

**Issue by aprudnikoff** [cytoscape/cytoscape.js-edgehandles#93]
I started with version 2.15.0 and in a couple of days suddenly found that 3.x had came out. But... I have no clues what I can expect from a new major release. Any bugfixes, new features, breaking changes?
It's a good practice to have it.

**Comment by maxkfranz** [comment]
There are typically one or a few changes per release, and those are listed in the commit logs.  You can `git log` to see the changes.

Maybe we could use the Github milestones in future for the extensions, but no one has ever asked for change logs before.  Since the extensions are all so small and simple, there is probably little value in doing that over just using `git log`.

**Comment by aprudnikoff** [comment]
Yes, I can do `git log`, but it takes some time to dig into and discover is there any breaking changes for example. Sometimes commit description is not enough for understanding.

**Comment by jacprada** [comment]
I agree, a changelog would be extremely useful and overall I would say it is good practice to have it. Are there any plans for it?

By the way, great work @maxkfranz! 🥇
